/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AggregatedCourseStatsDto { 
    courseId?: string;
    score?: number;
    courseCompletion?: number;
    examCompletion?: number;
}

