/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttemptStatus } from './attemptStatus';
import { SavedAnswerDto } from './savedAnswerDto';
import { QuestionDto } from './questionDto';


export interface AttemptDetailsDto { 
    id?: string;
    attemptResultId?: string | null;
    examId?: string;
    examTitle?: string;
    examDescription?: string | null;
    attemptNumber?: number;
    createdOn?: string;
    startedAt?: string;
    duration?: string | null;
    status?: AttemptStatus;
    questions?: Array<QuestionDto>;
    savedAnswers?: Array<SavedAnswerDto>;
}
export namespace AttemptDetailsDto {
}


