/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AttemptStatus = {
    InProgress: 'InProgress',
    Submitted: 'Submitted',
    Expired: 'Expired',
    Draft: 'Draft',
    Checked: 'Checked',
    PendingReview: 'PendingReview',
    PendingManualReview: 'PendingManualReview'
} as const;
export type AttemptStatus = typeof AttemptStatus[keyof typeof AttemptStatus];

