/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SavedAnswerDto } from './savedAnswerDto';
import { QuestionDto } from './questionDto';


export interface AttemptDetailsDto { 
    id?: string;
    examId?: string;
    examTitle?: string;
    createdOn?: string;
    startedAt?: string;
    questions?: Array<QuestionDto>;
    savedAnswers?: Array<SavedAnswerDto>;
}

