/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttemptResultRecordDto { 
    id?: string;
    attemptId?: string;
    examId?: string;
    courseId?: string;
    totalQuestions?: number | null;
    correctAnswers?: number | null;
    score?: number | null;
    maxScore?: number;
    scorePercentage?: number | null;
    evaluatedOn?: string;
    passed?: boolean | null;
}

