/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttemptResultDto } from './attemptResultDto';
import { AttemptDetailsDto } from './attemptDetailsDto';


export interface AttemptOverviewAggregateDto { 
    examTitle?: string;
    examDescription?: string | null;
    attemptResult?: AttemptResultDto;
    attemptDetails?: AttemptDetailsDto;
}

