/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionResultDto } from './questionResultDto';


export interface AttemptResultDto { 
    attemptId?: string;
    examId?: string;
    courseId?: string;
    totalQuestions?: number;
    correctAnswers?: number;
    score?: number;
    maxScore?: number;
    scorePercentage?: number;
    passed?: boolean;
    details?: Array<QuestionResultDto>;
}

