/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloomAnalysisDto } from './bloomAnalysisDto';
import { ExamAttemptDto } from './examAttemptDto';
import { AttemptResultRecordDto } from './attemptResultRecordDto';


export interface AttemptResultWithStatsDto { 
    attemptResult?: AttemptResultRecordDto;
    examAttempt?: ExamAttemptDto | null;
    bloomAnalytics?: BloomAnalysisDto;
}

