/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloomLevelPerformanceDto } from './bloomLevelPerformanceDto';
import { RecommendedMaterialDto } from './recommendedMaterialDto';


export interface BloomAnalysisDto { 
    id?: string;
    attemptResultId?: string;
    overallFeedback?: string | null;
    performanceByLevel?: Array<BloomLevelPerformanceDto>;
    recommendations?: Array<RecommendedMaterialDto>;
}

