/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const BloomLevel = {
    Evaluating: 'Evaluating',
    Creating: 'Creating',
    Analyzing: 'Analyzing',
    Applying: 'Applying',
    Understanding: 'Understanding',
    Knowing: 'Knowing'
} as const;
export type BloomLevel = typeof BloomLevel[keyof typeof BloomLevel];

