/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloomLevel } from './bloomLevel';


export interface BloomLevelPerformanceDto { 
    level?: BloomLevel;
    scorePercentage?: number;
    isWeakPoint?: boolean;
}
export namespace BloomLevelPerformanceDto {
}


