/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExamDetailsDto } from './examDetailsDto';
import { LectureDto } from './lectureDto';
import { TopicDto } from './topicDto';


export interface CourseAggregateDto { 
    title?: string;
    description?: string | null;
    authorId?: string;
    isFinished?: boolean;
    topics?: Array<TopicDto> | null;
    lectures?: Array<LectureDto> | null;
    exams?: Array<ExamDetailsDto> | null;
}

