/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CourseDto { 
    title?: string;
    description?: string | null;
    authorId?: string;
    lastUpdaterId?: string;
    isFinished?: boolean;
    isPublished?: boolean;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}

