/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOptionDto } from './createOptionDto';


export interface CreateQuestionDto { 
    text?: string;
    type?: number;
    scoreWeight?: number;
    checkingType?: number;
    level?: number;
    options?: Array<CreateOptionDto>;
}

