/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateQuestionDto } from './createQuestionDto';
import { EvaluationStrategy } from './evaluationStrategy';


export interface CreateExamDto { 
    title?: string;
    description?: string | null;
    topicId?: string | null;
    duration?: string;
    startsAt?: string;
    finishesAt?: string;
    minimalPassScore?: number | null;
    attemptsCount?: number;
    evaluationStrategy?: EvaluationStrategy;
    canSkip?: boolean;
    showResults?: boolean;
    canCheckAttempts?: boolean;
    isRandomOrder?: boolean;
    questions?: Array<CreateQuestionDto>;
}
export namespace CreateExamDto {
}


