/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloomLevel } from './bloomLevel';
import { CreateOptionDto } from './createOptionDto';
import { CheckingType } from './checkingType';
import { QuestionType } from './questionType';


export interface CreateQuestionDto { 
    text?: string;
    type?: QuestionType;
    scoreWeight?: number;
    checkingType?: CheckingType;
    level?: BloomLevel;
    options?: Array<CreateOptionDto>;
}
export namespace CreateQuestionDto {
}


