/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttemptStatus } from './attemptStatus';


export interface ExamAttemptDto { 
    id?: string;
    examId?: string;
    courseId?: string;
    attemptResultId?: string | null;
    userId?: string;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    userGroup?: string | null;
    status?: AttemptStatus;
    startedAt?: string;
    finishedAt?: string;
}
export namespace ExamAttemptDto {
}


