/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExamRecordDto { 
    title?: string;
    description?: string | null;
    courseId?: string;
    authorId?: string;
    lastUpdaterId?: string;
    topicId?: string | null;
    duration?: string;
    startsAt?: string;
    finishesAt?: string;
    minimalPassScore?: number;
    attemptsCount?: number;
    canCheckAttempts?: boolean;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}

