/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EvaluationStrategy } from './evaluationStrategy';
import { QuestionDto } from './questionDto';


export interface ExamDetailsDto { 
    title?: string;
    description?: string | null;
    courseId?: string;
    authorId?: string;
    lastUpdaterId?: string;
    topicId?: string | null;
    duration?: string;
    startsAt?: string;
    finishesAt?: string;
    minimalPassScore?: number;
    attemptsCount?: number;
    evaluationStrategy?: EvaluationStrategy;
    canSkip?: boolean;
    showResults?: boolean;
    canCheckAttempts?: boolean;
    isRandomOrder?: boolean;
    questions?: Array<QuestionDto>;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}
export namespace ExamDetailsDto {
}


