/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NullableOfBloomLevel } from './nullableOfBloomLevel';


export interface LectureDetailsDto { 
    title?: string;
    description?: string | null;
    content?: string;
    targetBloomLevel?: NullableOfBloomLevel | null;
    courseId?: string;
    topicId?: string | null;
    authorId?: string;
    lastUpdaterId?: string;
    contentLinks?: Array<string> | null;
    filePaths?: Array<string> | null;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}
export namespace LectureDetailsDto {
}


