/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const NullableOfCheckingType = {
    Automatic: 'Automatic',
    Manual: 'Manual'
} as const;
export type NullableOfCheckingType = typeof NullableOfCheckingType[keyof typeof NullableOfCheckingType];

