/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const NullableOfBloomLevel = {
    Knowing: 'Knowing',
    Understanding: 'Understanding',
    Applying: 'Applying',
    Analyzing: 'Analyzing',
    Creating: 'Creating',
    Evaluating: 'Evaluating'
} as const;
export type NullableOfBloomLevel = typeof NullableOfBloomLevel[keyof typeof NullableOfBloomLevel];

