/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuestionResultDto { 
    questionId?: string;
    text?: string;
    score?: number;
    maxScore?: number;
    isCorrect?: boolean;
    comment?: string | null;
    questionResultStatus?: number;
    selectedOptionIds?: Array<string> | null;
    freeTextAnswer?: string | null;
    correctOptionIds?: Array<string> | null;
    correctAnswerText?: string | null;
}

