/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloomLevel } from './bloomLevel';
import { CheckingType } from './checkingType';
import { QuestionType } from './questionType';
import { OptionForUpdateDto } from './optionForUpdateDto';


export interface QuestionForUpdateDto { 
    text?: string;
    type?: QuestionType;
    level?: BloomLevel;
    checkingType?: CheckingType;
    scoreWeight?: number;
    options?: Array<OptionForUpdateDto>;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}
export namespace QuestionForUpdateDto {
}


