/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptionDto } from './optionDto';


export interface QuestionDto { 
    text?: string;
    type?: number;
    level?: number;
    checkingType?: number;
    options?: Array<OptionDto>;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}

