/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloomLevel } from './bloomLevel';


export interface RecommendationTemplateDto { 
    id?: string;
    targetLevel?: BloomLevel;
    adviceText?: string;
    courseId?: string | null;
}
export namespace RecommendationTemplateDto {
}


