/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterUserDto { 
    email?: string;
    password?: string;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    group?: string | null;
    faculty?: string | null;
    enteringDate?: string | null;
    graduationDate?: string | null;
}

