/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserProfileDto { 
    firstName?: string | null;
    middleName?: string | null;
    lastName?: string | null;
    group?: string | null;
    faculty?: string | null;
    avatarUrl?: string | null;
}

