/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateRecommendationTemplate { 
    targetLevel?: number | null;
    adviceText?: string | null;
    courseId?: string | null;
}

