/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateLecture { 
    title?: string | null;
    description?: string | null;
    content?: string | null;
    courseId?: string | null;
    topicId?: string | null;
    contentLinks?: Array<string> | null;
    filePaths?: Array<string> | null;
}

