/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NullableOfBloomLevel } from './nullableOfBloomLevel';


export interface UpdateRecommendationTemplate { 
    targetLevel?: NullableOfBloomLevel | null;
    adviceText?: string | null;
    courseId?: string | null;
}
export namespace UpdateRecommendationTemplate {
}


