/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateQuestionDto } from './updateQuestionDto';


export interface UpdateExamDto { 
    title?: string | null;
    description?: string | null;
    courseId?: string | null;
    topicId?: string | null;
    duration?: string | null;
    startsAt?: string | null;
    finishesAt?: string | null;
    minimalPassScore?: number | null;
    attemptsCount?: number;
    canSkip?: boolean | null;
    showResults?: boolean | null;
    canCheckAttempts?: boolean | null;
    isRandomOrder?: boolean | null;
    questions?: Array<UpdateQuestionDto> | null;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}

