/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NullableOfBloomLevel } from './nullableOfBloomLevel';
import { NullableOfCheckingType } from './nullableOfCheckingType';
import { NullableOfQuestionType } from './nullableOfQuestionType';
import { UpdateOptionDto } from './updateOptionDto';


export interface UpdateQuestionDto { 
    id?: string | null;
    text?: string | null;
    type?: NullableOfQuestionType | null;
    scoreWeight?: number | null;
    checkingType?: NullableOfCheckingType | null;
    level?: NullableOfBloomLevel | null;
    options?: Array<UpdateOptionDto> | null;
}
export namespace UpdateQuestionDto {
}


