/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateOptionDto { 
    text?: string;
    isCorrect?: boolean;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}

