/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateOptionDto } from './updateOptionDto';


export interface UpdateQuestionDto { 
    text?: string | null;
    type?: number | null;
    scoreWeight?: number | null;
    checkingType?: number | null;
    level?: number | null;
    options?: Array<UpdateOptionDto> | null;
    id?: string;
    createdOn?: string | null;
    updatedOn?: string | null;
}

