/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserBaseInformationDto { 
    id?: string;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    group?: string | null;
    faculty?: string | null;
}

