/**
 * DPBloom | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileDto { 
    id?: string;
    userName?: string;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    email?: string;
    group?: string | null;
    faculty?: string | null;
    avatarUrl?: string | null;
    fullName?: string | null;
    roles?: Array<string>;
    firstLogin?: string;
    lastLogin?: string;
    createdOn?: string;
    enteringDate?: string | null;
    graduationDate?: string | null;
}

